const GITHUB_USERNAMES = [
  "shibisuriya",
  "OrangeScape",
  "Arun-Palanivel",
  "EswaraMoorthyB",
  "HemapriyaG",
  "Joshua-Prakasam",
  "Muthuponmari",
  "Prasannasm",
  "Prashannabalaji",
  "Pravallikakotha",
  "Purushot14",
  "Ramprasad-2809",
  "RojaMulagala",
  "Rv-Vignesh",
  "Sivagnanam-M",
  "SowmyaLR",
  "adhiramanathan",
  "arjun-g",
  "chanakyan-arivumani",
  "itsparser",
  "jayanthsn",
  "kbtganesh",
  "krithika728",
  "lokeshkandala",
  "mraghuram3",
  "parthasarathygopu",
  "prasannaSM",
  "prashanth9962",
  "rajesh-arunachalam",
  "sairam459",
  "sangeethkumar22",
  "saravanan10393",
  "sathishos",
  "saravanakesavan",
  "vivekmadurai",
  "yadhus",
  "rakeshar3796",
  "jimisaacd",
  "sureshsaics",
  "VimalKumarM",
  "ip-aka-ilamparithi",
  "ganeshpandian09",
  "parthipanj",
  "Gowthaman-Ganesan",
  "gopal1996",
  "indhumathi-n",
  "sriharan04",
  "Poorvighakissflow",
  "vasudevan-vishal",
  "gokul2104",
  "Sangeethshiv36",
  "themonks",
  "siva-kannan3",
  "satheesh66",
  "manu2699",
  "AnjannaOS",
  "barath-kissflow",
  "Dhananjayan-MS",
  "mageshkumar1598",
  "ajay-kissflow",
  "sprpremkumar",
  "dhiwakar1997",
  "Prithviraj-kf",
  "noordeen03",
  "iamchandugr",
  "Aravinthan-J",
  "Venkadeshkissflow",
  "CHARANREDDY-learntocode",
  "Jenifersingh",
  "sathyasubramanianv",
  "nikson-as",
  "RohithKissflow",
  "karthikeswar17",
  "vasanthkumar10",
  "balamurugan-v",
  "karunakaranks",
  "Joish",
  "gokulsp98",
  "mohanrajkissflow",
  "abdul-kissflow",
  "Sankarck2",
  "kaaviya-n",
  "KarthikAravindR",
  "Dharani-Naveen",
  "kavilakshmi",
  "mukilan007",
  "jyothiprakash-frontend",
  "Jai1625",
  "shriramnkf",
  "vaibhavmano",
  "Mani6027",
  "thilak-mani-b",
  "KarthickSakthi",
  "saranraja-thiyagu",
  "ragavavishal",
  "soundar-surya",
  "Vimal-Kumar-V",
  "pvrameshkf",
  "Shibhu-ganesan",
  "IamAravindKumar",
  "s-ashwin",
  "Abhinivesh001",
  "SaiDeepak26",
  "GOWTHAM-EV",
  "viswaa99",
  "gopinath-r-kflow",
  "narmadha-raghu",
  "ram-sankar-ask",
  "RashmiSubramani",
  "Mukesh-R",
  "Malavikaselvan765",
  "SSivakrishnan",
  "syed-saif",
  "GuruM274",
  "karthik-noveau",
  "staticGuru",
  "nknantha",
  "akshayalashmik",
  "Sakthi-S-M",
  "anu2319",
  "roshinirs",
  "Muthukumar04",
  "SrimathiS14",
  "muthuram05",
  "notAravind",
  "Priyanka-Vijaykumar2803",
  "NPNShanthoshnarayanan",
  "jkobjacob",
  "Albinbritto",
  "SusmithaVasudevan",
  "sherin-kissflow",
  "Sai-Venkata-Krishnan",
  "SridharCR1",
  "Jayalakshmi-23",
  "kannasuresh99",
  "iamadhee",
  "mathankf",
  "Pavikissflow",
  "Deepikashree22",
  "Shankar-ganesh-N",
  "Arun07L",
];

const ENVIRONMENTS = [
  "assist",
  "ana",
  "anaqa",
  "app",
  "appqa",
  "bo",
  "boqa",
  "channel",
  "channelqa",
  "chat",
  "chatqa",
  "community",
  "communityqa",
  "fec",
  "fecqa",
  "form",
  "integration",
  "integrationqa",
  "lcnc",
  "lcncqa",
  "leo",
  "leoqa",
  "lyra",
  "lyraqa",
  "MCH",
  "MCHqa",
  "pnr",
  "pnrqa",
  "project",
  "projectqa",
  "skat",
  "skatqa",
  "sns",
  "snsqa",
  "spd",
  "spdqa",
  "virgo",
  "virgoqa",
];

const SERVICES = {
  "account-client": "devAccountClient",
  "application-client": "devApplicationClient",
  "base-client": "devBaseClient",
  "case-client": "devCaseClient",
  "dataset-client": "devDatasetClient",
  "form-client": "devFormClient",
  "integration-client": "devIntegrationClient",
  "list-client": "devListClient",
  "main-client": "devMainClient",
  "page-client": "devPageClient",
  "process-client": "devProcessClient",
  "project-client": "devProjectClient",
  "report-client": "devReportClient",
  "platform-client": "devPlatformClient",
  "widgets-client": "devWidgetsClient",
  "analytics-client": "devAnalyticsClient",
  "components-client": "devComponentsClient",
  "appstore-client": "devAppstoreClient",
  "externaldata-client": "devExternalDataClient",
  "decisiontable-client": "devDecisionTableClient",
  "assist-client": "devAssistClient",
};

export { ENVIRONMENTS, GITHUB_USERNAMES, SERVICES };
